services:
  rotmg-daily-webserver:
    container_name: rotmg-daily-webserver
    #image: node:20-buster
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "3001:3001"
    volumes:
      - rotmg-daily-web:/app
    tty: true
    stdin_open: true
  
volumes:
  rotmg-daily-web: